# PyCon JP 2025 Setting

[page]
url = "https://2025-live-dev.pycon.jp/"

[page.cors]
origin = "https://2025-live-dev.pycon.jp"
method = "*"
header = "*"

[api.pretix]
base = "https://pretix.eu"
organizer = "pyconjp"
redirect_uri = "https://auth.streamtech.cloud/callback"

[api.jstream]
wlive = "api-dev.stream.co.jp/v2.0/wlives"
hlsauth = "api-dev.stream.co.jp/v2.0/service/hlsauth"
session = "hls-auth-sess-stg.cloud.stream.co.jp/v2.0"

[live]
pretix_live_ticket_id = 835615
authenticated_url = "https://hls-auth-stg.cloud.stream.co.jp/auth/index.m3u8?session_id={session_id}"

[[live.track]]
track = 1
live_id = "q2bh41a7syfx3v2c"
stream_id = "621134ad-121a-4e92-b6e9-ea09de54e884"

[[live.track]]
track = 2
live_id = "l0b9htfynst37t45"
stream_id = "fe72bd0e-6c27-4b9d-85fc-f1b59f91df8b"

[[live.track]]
track = 3
live_id = "q8mbz426wpl96cy6"
stream_id = "2509643d-7e23-4719-88b9-99f119040adb"

[[live.track]]
track = 4
live_id = "j34il2934not3vda"
stream_id = "250db474-6d80-4d22-8d4d-5c14ffa3c388"
